### ISSUE TITLE
Can't install Revealables package

### ISSUE THREAD

**Issue by yurket** [sisl/Revealables.jl#9]
Hi guys! can't install the package with julia 1.6.0 on Gentoo:
```
(@v1.6) pkg> add Revealables
ERROR: The following package names could not be resolved:
 * Revealables (not found in project, manifest or registry)
```
I indeed can't find the package in General registry, so if it was deleted, maybe it worh adding a note in README?
Thanks!

**Comment by mykelk** [comment]
Updated to Julia 1 and registered!
